<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="Simple2DoFManipulator">

  <xacro:property name="link1_length" value="1.0" />
  <xacro:property name="link2_length" value="0.5" />

  <link name="Root">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.1"/>
      </geometry>
      <material name="">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>
  </link>

  <joint name="Joint1" type="revolute">
    <parent link="Root"/>
    <child link="Link1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0.0" upper="${pi/2}" effort="1e6" velocity="1e6"/>
  </joint>
  <link name="Link1">
    <visual>
      <geometry>
        <cylinder length="0.2" radius="0.075"/>
      </geometry>
      <material name="">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>
    <visual>
      <origin xyz="${link1_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${link1_length} 0.075 0.2"/>
      </geometry>
      <material name="">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>
    <visual>
      <origin xyz="${link1_length} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.2" radius="0.075"/>
      </geometry>
      <material name="">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>
  </link>

  <joint name="Joint2" type="revolute">
    <parent link="Link1"/>
    <child link="Link2"/>
    <origin xyz="${link1_length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0.0" upper="${pi}" effort="1e6" velocity="1e6"/>
  </joint>
  <link name="Link2">
    <visual>
      <geometry>
        <cylinder length="0.3" radius="0.05"/>
      </geometry>
      <material name="">
        <color rgba="0 0.8 0 1"/>
      </material>
    </visual>
    <visual>
      <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${link2_length} 0.05 0.3"/>
      </geometry>
      <material name="">
        <color rgba="0 0.8 0 1"/>
      </material>
    </visual>
    <visual>
      <origin xyz="${link2_length} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.3" radius="0.05"/>
      </geometry>
      <material name="">
        <color rgba="0 0.8 0 1"/>
      </material>
    </visual>
  </link>

  <joint name="EEF" type="fixed">
    <parent link="Link2"/>
    <child link="EEF"/>
    <origin xyz="${link2_length} 0 0" rpy="0 0 0"/>
  </joint>
  <link name="EEF">
    <visual>
      <geometry>
        <cylinder length="0.4" radius="0.025"/>
      </geometry>
      <material name="">
        <color rgba="0.8 0 0 1"/>
      </material>
    </visual>
  </link>
</robot>
