# Interval of loop counts to publish ROS message
publish_loop_interval: 100

# Robot root pose
root_pose:
  # translation: [0, 0, 0.7] # Foot
  translation: [0, 0, 0.0] # Hand

# Body name list for collision avoidance
collision_body_names_list:
  ["Body", "Larm_Link2",
  "Body", "Larm_Link3",
  "Body", "Larm_Link4",
  "Body", "Lhand_Link0_Plan2",
  "Chest_Link2", "Larm_Link2",
  "Chest_Link2", "Larm_Link3",
  "Chest_Link2", "Larm_Link4",
  "Chest_Link2", "Lhand_Link0_Plan2"]

# Weight of collision task
collision_task_weight: 1

# Number of samples to make bounding box
bbox_sample_num: 1000

# Padding rate of bounding box
# bbox_padding_rate: 0.6 # Foot
bbox_padding_rate: 1.2 # Hand

# Number of IK trial
ik_trial_num: 1

# Number of IK loop
ik_loop_num: 50

# Threshold of IK [m], [rad]
ik_error_thre: 5e-3

# Constraint space of IK (default is same as template parameter SamplingSpaceType)
# ik_constraint_space: SE3 # Foot
ik_constraint_space: R3 # Hand
