# Rate in runLoop()
loop_rate: 5000

# Step interval to publish in runLoop()
publish_interval: 100

# Height of xy plane marker
svm_thre: -0.1

# Limit of configuration update in one step [m], [rad]
delta_config_limit: 0.005

# Initial sample pose list
initial_sample_pose_list:
  - translation: [0.0, 0.0, 0.0]
  - translation: [0.0, 0.0, 0.0]
  - translation: [0.0, 0.0, 0.0]

# Number of footsteps
motion_seq_len: 3

# Regularization weight
reg_weight: 1e-6

# Adjacent regularization weight
adjacent_reg_weight: 1e-3

# QP objective weight for SVM inequality error
svm_ineq_weight: 1e6

# Vertices of foot marker
foot_vertices: [
  [-0.07, -0.035, 0.01],
  [-0.065, -0.04, 0.01],
  [0.06, -0.04, 0.01],
  [0.085, -0.02, 0.01],
  [0.085, 0.02, 0.01],
  [0.06, 0.04, 0.01],
  [-0.065, 0.04, 0.01],
  [-0.07, 0.035, 0.01]
  ]
